course_name = "大学物理实验"
repo_type = "normal"
course_code = "PHYS1002"

description = """
{{< callout type="info" >}}
自 `2024.03.20` 开始，由于大物实验每年安排的不确定性，原 **大学物理实验 IA (PHYS1002A)** 与 **大学物理实验 IB (PHYS1002B)** 仓库现采用统一的命名方式，合并成 **大学物理实验 (PHYS1002)** 页面。

本学期不再采用的实验资料转移至 `archived` 文件夹。
{{< /callout >}}

这门课只有 1 学分，然而总共有 20 学时以上要求，相当费时费力，所以我们的应对办法就是将省事的工具集中起来，让选做各种物理实验的同学们能更快地完成实验外的工作。
"""

[[sections]]
title = "新人须知"

[[sections.items]]
content = """
大一春季学期开学后，会安排一节大学物理实验绪论课（23 级以前是 4 学时，24 级改成了 2 学时，意味着实验要求学时增加了 2 学时），介绍大学物理实验课程的基本内容、实验要求、数据处理方式、实验报告要求，并会有一次绪论课作业，**此次作业算作一次实验计入最终成绩的计算！**

物理实验需要开放选课后在单独的选课平台上，从大约十多个实验中，选足课程要求学时的实验完成。这些实验中大多是 2 学时（1 节大课），少数为 4 学时（2 节大课）。

2024 年春季学期要求可以作为参考：

- 大物实验 A 共 12 个实验，要求完成 20 学时实验课时
- 大物实验 B 共 13 个实验，要求完成 24 学时实验课时

每一个实验在该学期内会设置很多课次，在选课平台开放前会提供本学期课次安排表。开放选课平台后，需要学生自己选择上哪一个课次。由于选课平台独立于本研平台，**_无法查看实验与正常课程的冲突情况，需手动核对冲突_** ~~不可否认，这能给予我们极大操作空间~~。你可以将实验选在学期初避免占用期末周，也可以将实验选在学期后期，这样时间 ~~（或许？）~~ 更充足。选课系统在实验排课结束前随时可以登录对自己的选课进行修改：已经错过时间的实验无法退课，只能补做；还未上课的实验可以退课，也可以补选仍有空位的实验。

实验安排的课次结束后，会开放一周的时间给仍为完成要求课时实验的同学进行补做，之前错过实验的同学也可以前往补做。

每次实验前要完成实验预习（要求手写，但可以使用平板完成）并在课前交由老师检查，实验做完后需要在规定日期前提交实验报告（2023 年是实验后两周内，2024 年实验报告都是期末统一批改，实际上并没有两周内提交报告的硬性要求），报告使用 pdf 格式（21 级之前只能交纸质，甚至**手写**，曾经出现过老师弄丢报告的情况，因此全部使用电子版提交，提交到指定的邮箱）。实验报告需要有预习部分的打分和实验原始数据记录的教师签名，课上只要求完成原始数据的记录，课后完成其余内容。

> [!CAUTION]
> **警告：直接抄仓库内的实验数据作为自己的实验数据属于造假行为，造假行为一旦被发现将被严肃处理！**
> 
> 请谨慎考虑随意引用数据可能导致的任何后果，一旦被发现不仅本门成绩记零，还可能受到学校的处分。
> 
> 我们绝不支持照抄仓库内的实验数据，本仓库的正确使用方法应该是合理使用仓库中的画图工具和计算工具更好的完成实验。

### 选什么实验呢？

这应该是同学在选实验的时候最关心的问题。
首先，你选的实验总学时要满足学时要求；其次，不管你是否卷学分绩，你大概希望花在实验上的时间越少越好，也就是说，实验越简单越好。

根据本人一学期下来的经验，我认为评价一个实验难不难，就看 3 点：**实验操作成功率**、**是否要计算不确定度**、**是否要绘图**。

1. 实验操作成功率：这个指的是实验的操作是否容易出错，导致记录的数据有误无法通过检查或得不到理想结果。如果操作失误，就会在课上耽误很多时间去校正结果。这一点主要看个人的操作能力。

2. 计算不确定度：实验报告中最麻烦的步骤就是计算测量物理量的不确定度。因此那些不需要计算不确定度的实验应该是你优先的选择。
3. 绘图：实验报告还有可能让你绘制一些统计图。当然现在的实验报告使用的是电子版，所以可以尽情地使用各种绘图软件。仓库中需要绘图的实验基本上都有我们上传的程序，因此这一点对于实验难度的影响有限。

每个实验文件夹下的 `README.md` 文件中都有对应实验的一些描述，你可以参考这些评价来选择你的实验。
> [!Note]
> 当然，这里必须提到一类特殊的实验：**虚拟仿真实验**。这些实验需要在物理实验仿真平台上进行实验操作和数据记录。
> 实验完成后，学生需要将记录的数据上传提交，平台会将提交的数据和标准答案进行比对，给出一个实验成绩。
> 如果实验后觉得分数不够高，还可以自己在平台上重新做一次。
> 实验都是在程序中的理想环境中进行的，因此不需要担心实验仪器的质量问题。
> 虚拟仿真实验都有学习模式和实验模式两个模式，做完一个模式后**不要退出实验而是回到主页进入另一个模式完成**，否则实验成绩只有一个模式的成绩（50-）
"""
author = [
  { name = "Maxwell Jay", link = "https://github.com/MaxwellJay256", date = "2023-12" },
  { name = "Longlin Li", link = "https://github.com/longlin10086", date = "2024-04" },
  { name = "Gaster", link = "https://github.com/WDGaster703", date = "2025-03" },
]

[[sections]]
title = "目录与个人仓库"

[[sections.items]]
content = """
考虑到开设的实验列表每年都有变化，因此以下仓库是对历史开设实验的记录，不再区分「本学年开设的实验」，可以使用浏览器查找功能寻找需要的实验。**_由于实验列表及学分有可能变化，还望后来者及时补充。_**

尽管有资料下载界面，下面仍列出 GitHub 仓库名，其原因是，用于画图的部分代码文件及其操作说明（README）文件可能需要进入 GitHub 仓库才能看到，希望大家学会访问 GitHub。可以使用魔法，也可以参考教程：[新人指南：不使用第三方工具访问 GitHub](https://hoa.moe/blog/access-github/)。

|   编号   |                 实验名称                 |                        文件夹链接<br>(GitHub 仓库)                         | 学时 |
| :------: | :--------------------------------------: | :------------------------------------------------------------------------: | :--: |
|    01    |           用示波器观测磁滞回线           |    [Exp01](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp01)    |  2   |
|    02    |           拉伸法测杨氏弹性模量           |    [Exp02](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp02)    |  2   |
|    03    |              液体黏度的测定              |    [Exp03](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp03)    |  2   |
|    04    |             薄透镜焦距的测定             |    [Exp04](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp04)    |  2   |
|    05    |            用惠斯通电桥测电阻            |    [Exp05](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp05)    |  2   |
|    06    |     磁耦合谐振式无线电力传输实验研究      |    [Exp06](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp06)    |  4   |
|    07    |             空气中声速的测量             |    [Exp07](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp07)    |  2   |
|    08    |              迈克尔逊干涉仪              |    [Exp08](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp08)    |  4   |
|    09    |       电子电荷的测定——密立根油滴法       |    [Exp09](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp09)    |  4   |
|    10    |              霍尔效应及其应用          |    [Exp10](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp10)    |  4   |
|    11    |         太阳能电池的基本特性研究         |    [Exp11](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp11)    |  2   |
|    12    |           液体表面张力系数测量           |    [Exp12](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp12)    |  2   |
|    13    |            自组显微镜与望远镜            |    [Exp13](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp13)    |  4   |
|    14    |            分光计的调节及应用            |    [Exp14](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp14)    |  4   |
|    15    |          光的等厚干涉现象与应用          |    [Exp15](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp15)    |  2   |
|    16    |   准稳态法测不良导体的比热容和导热系数   |    [Exp16](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp16)    |  2   |
|    17    |       全息技术实验（虚拟仿真项目）       |    [Exp17](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp17)    |  4   |
|    18    |          RLC 电路暂态特性的研究          |    [Exp18](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp18)    |  2   |
|    19    |            双光栅检测微弱振动            |    [Exp19](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp19)    |  2   |
|    20    |             巨磁阻效应与应用             |    [Exp20](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp20)    |  2   |
|    21    |             弗兰克-赫兹实验              |    [Exp21](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp21)    |  2   |
|    22    |         光电效应法测定普朗克常量         |    [Exp22](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp22)    |  2   |
|    23    |       磁光效应及其在光通信中的应用       |    [Exp23](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp23)    |  2   |
|    24    |           液晶电光效应及其应用           |    [Exp24](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp24)    |  4   |
|    25    | 红外波的物理特性及其研究（虚拟仿真项目） |    [Exp25](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp25)    |  2   |
|    26    |     光强调制法测光速（虚拟仿真实验）     |    [Exp26](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp26)    |  2   |
|    27    |            自组光栅光谱仪实验          |    [Exp27](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp27)    |  4   |
|    28    |               碰撞打靶实验            |    [Exp28](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp28)    |  2   |
|    29    |        示波器实验（虚拟仿真项目）       |    [Exp29](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/Exp29)    |  2   |
| archived |        过于陈旧不太可能开展的实验        | [archived](https://github.com/HITSZ-OpenAuto/PHYS1002/tree/main/archived) |  省略  |

### 个人实验仓库收集

> 已得到仓库所有者授权的引用许可。

- [LittleYe233/hitsz-physics-ib-reports](https://github.com/LittleYe233/hitsz-physics-ib-reports)
- [Doctxing/phytex](https://github.com/Doctxing/phytex)：[Doctxing](https://github.com/Doctxing) 同学制作的 LaTeX 模板及数据处理程序
- [longlin10086/HITSZ-PhTyp](https://github.com/longlin10086/HITSZ-PhTyp): 一个大物实验报告的 Typst 模板
- [Zjl37/phys1006-workspace](https://github.com/Zjl37/phys1006-workspace): 动量子的大物实验工作区，含有实验报告的 Typst 模板和一些数据处理程序

"""

[[sections]]
title = "关于本仓库与贡献"

[[sections.items]]
content = """
每个人选择的物理实验不同，一个人即使上传了自己全部的实验资料也不能覆盖到所有人的需求；仓库的几位维护者在一学期内也不一定做了全部的实验。

如果你发现某个实验下的 `README.md` 文件缺少内容，或者想添加自己的评价，都可以通过 Pull Request 或 将文件打包发送邮件至 [📮hi@hoa.moe](mailto:hi@hoa.moe) 的方式来贡献你的想法。

即使是已经有人上传了资料的实验，你也可以在这个实验的目录下添加自己的版本，把你的资料放进去。
我们建议你上传这些内容：

- 实验报告的 pdf 成品
- 用来画图或数据处理的源程序，使用任何编程语言均可

注意，**不要随意改动或删除别人的资料**！

同时，非常欢迎大佬能为这些物理实验制作 LaTeX 或 Typst 等模版，
这样对于熟悉这些排版系统的人来说会更加方便。
"""
