name: Trigger Workflow in hoa-moe

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in hoa-moe
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          echo ${REPO_NAME}
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/HITSZ-OpenAuto/hoa-moe/actions/workflows/course-single.yaml/dispatches \
            -d '{"ref":"main","inputs": {"repo_name": "'"${REPO_NAME}"'"}}'
